#Notas Escolares - datos UTF-8. No editar mientras el programa este abierto.
#Tue Sep 15 21:40:20 COT 2026
1020245199.clave=210000$xkNbwlYZNmF9OJMaiNF1YQ\=\=$jyNe4K26P8FoYcKEn0MZhmGeEMw++oyERLy3LIjT8VY\=
1020245199.nombre=steban muños gallego
1020245199.tipoDocumento=TI
1020245199.aula=204
