#Notas Escolares - datos UTF-8. No editar mientras el programa este abierto.
#Tue Sep 15 21:41:22 COT 2026
1020245199.bWF0ZW1hdGljYXM.estudiante=1020245199
1020245199.bWF0ZW1hdGljYXM.materia=matematicas
1020245199.bWF0ZW1hdGljYXM.notas=3
