#Notas Escolares - datos UTF-8. No editar mientras el programa este abierto.
#Tue Sep 15 21:39:07 COT 2026
1018245199.nombre=manuel antonio mora giraldo
1018245199.clave=210000$MCt/tDD9rG2QkEij8A7BqA\=\=$CXDCzYcyoB5aW1lfsNZqIhOawCsMxuTO3+yKPAPsssU\=
1018245199.aula=204
